apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: javadeploy
spec:
  selector:
    matchLabels:
      app: java
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: java
    spec:
      containers:
        - name: minikube
          image: shreyaraghuvanshi1/docker_repo:latest # Image that will be used to containers in the cluster
          imagePullPolicy: Always
          restartPolicy: Never 
          ports:
            - containerPort: 80 # The port that the container is running on in the cluster
          resources:
            limits:
        # Maximum memory
              memory: "1Gi"
        # Maximum CPU usage
              cpu: "1000m"  
      


---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: dockerrepo
spec:
  selector:
    app: java
  ports:
    - protocol: "TCP"
      port: 80 # The port that the service is running on in the cluster
      targetPort: 80 # The port exposed by the service
  type: NodePort # type of the service.


